### ISSUE TITLE
possible lightcurve discrepancy/error

### ISSUE THREAD

**Issue by basuparth** [gammapy/enrico#134]
I was working on the source 1ES1218+304 and found some points in the lightcurve with suspiciously small errorbars and also indications of variability. On investigating the same time period by generating aperture lightcurves following the official fermi tutorial I found that during the time interval where enrico_lc shows a high peak there are actually no data points in the aperture_lc generated plots. 
![1ES1218+304_LCmonthly](https://user-images.githubusercontent.com/47746249/55273495-58fc3e00-52f2-11e9-92dc-9c8931b4e540.png)

![Aperture_LC](https://user-images.githubusercontent.com/47746249/55273501-66b1c380-52f2-11e9-92cc-3c8e71e13984.png)

**Comment by jmsantander** [comment]
MJD 58200 corresponds to the end of March 2018 when the spacecraft had an issue with the solar panel drives and the instruments were turned off for a while (https://www.nasa.gov/feature/goddard/2018/fermi-status-update/). There's no data for that period and therefore there's a gap in the light curves. 

In the top plot the point with zero uncertainty is in fact an upper limit, since you have very little data due to that gap.

**Comment by basuparth** [comment]
Thanks @jmsantander.
